### PR TITLE
Added scope as a prop

### PR DESCRIPTION
**Pull request by ignaciosantise**
## Summary
* Added scope as a prop to google.js. If scope is not sended, it uses the default value defined in the file

### CODE REVIEW

**Comment by ignaciosantise** [comment]
@adamjmcgrath can you check this?

**Comment by adamjmcgrath** [comment]
Linting is failing, otherwise lgtm

```
/home/travis/build/adamjmcgrath/react-native-simple-auth/lib/providers/google.js
  48:1  error  Line 48 exceeds the maximum line length of 80  max-len
```

**Comment by ignaciosantise** [comment]
Solved! 😄

**Comment by adamjmcgrath** [comment]
Thanks, will do a release shortly

**Comment by adamjmcgrath** [comment]
+ react-native-simple-auth@2.3.0

**Pull request merged**
